Repository ESN-Croatia-IT/CEE-Web, pull requests merged in 2025-05, with the labels that each got.

#68 Header subpages
  about_us.html
  components/dropdownlist.html
  components/header.html
  contacts.html
  faq.html
  homepage.html
  images/header_img2.png
  images/header_img3.png
  scripts/change-bg.js
  scripts/component-joiner.js
  scripts/countdown.js
Labels: bug/fix, feature

#70 Content
  components/dropdownlist.html
  components/footer.html
  components/header.html
  components/navbar.html
  contacts.html
  faq.html
  homepage.html
  images/oc/anamarija.jpeg
  images/oc/bruno.jpeg
  images/oc/ema.jpeg
  images/oc/iva.jpeg
  images/oc/ivana.jpeg
  images/oc/maida.jpeg
  images/perks/accomodation_image.jpg
  images/perks/food-image.jpg
  images/perks/location_image.jpg
  images/perks/transport_image.jpg
  scripts/countdown.js
Labels: feature

#71 Modify FAQ to use clear language
  faq.html
Labels: bug/fix

#72 Add Prettier config & Tailwind prettier plugin
  .prettierrc
  components/dropdownlist.html
  components/footer.html
  components/header.html
  contacts.html
  faq.html
  homepage.html
  package-lock.json
  package.json
Labels: system/refactor
